name: news_app_flutter_class
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.0
  flutter_native_splash: ^2.2.19
  get:
  shared_preferences:
  gap:
  hive:
  dio:
  timeago:
  sizer:
  shimmer_animation:
  smooth_page_indicator:
  cached_network_image:
  path_provider:
  flashy_tab_bar2: ^0.0.6
  flutter_card_swiper: ^5.0.0

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/icons/app_icon.png'
  image_dark: 'assets/icons/app_icon.png'
  android: true
  ios: true
  web: true
  color_dark: '#1a1a1a'
  android_gravity: center

icons_launcher:
  image_path: "assets/icons/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/
     - assets/icons/
     - assets/images/
     - assets/images/bg.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

